version: "3.8"

services:
  service-config:
    container_name: service-config
    build: ./service-config
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=service-config
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/bosley001/cloud-conf
    networks:
      - microservices-network

  service-registry:
    container_name: service-registry
    build: ./service-registry
    depends_on:
      - service-config
    ports:
      - "8081:8761"
    environment:
      - SPRING_APPLICATION_NAME=service-registry
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8080
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8080
    networks:
      - microservices-network

  service-proxy:
    container_name: service-proxy
    build: ./service-proxy
    depends_on:
      - service-config
      - service-registry
    ports:
      - "8082:8079"
    environment:
      - SPRING_APPLICATION_NAME=service-proxy
      - SPRING_CLOUD_CONFIG_URI=http://service-config:8080
      - SPRING_CONFIG_IMPORT=configserver:http://service-config:8080
    networks:
      - microservices-network

  auth-service:
    container_name: auth-service
    build: ./auth-service
    depends_on:
      - service-config
      - service-registry
    ports:
      - "8083:9010"
    environment:
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=5432
      - EUREKA_HOST=service-registry:8761
    networks:
      - microservices-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices-network

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=notification_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservices-network

  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=tsore
      - POSTGRES_PASSWORD=tsore
      - POSTGRES_DB=auth_tsore
    ports:
      - "5432:5432"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  mysql_data:
